id: A2E3BF133
base_file: f87F8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:35:37.011410
  last_modified_at: 2022-06-11 13:35:37.011417
