id: A2E3BF133
base_file: fAA1D.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:35:37.013475
  last_modified_at: 2022-06-11 13:35:37.013479
