id: A2E3BF133
base_file: fACBB.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:35:37.014940
  last_modified_at: 2022-06-11 13:35:37.014943
